---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-clickhouse-storage-template-0
  labels:
    type: clickhouse-data
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /mnt/clickhouse/datadir-0
    type: DirectoryOrCreate
---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: pv-clickhouse-storage-template-1
#   labels:
#     type: clickhouse-data
# spec:
#   capacity:
#     storage: 50Gi
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: local-path
#   hostPath:
#     path: /mnt/clickhouse/datadir-1
#     type: DirectoryOrCreate
