- name: Install and configure ClickHouse
  hosts: localhost
  gather_facts: false

  vars:
    namespace_name: clickhouse

  tasks:
    - name: Check if namespace exists
      kubernetes.core.k8s_info:
        kind: Namespace
        name: "{{ namespace_name }}"
      register: namespace_check
      changed_when: false

    - name: Create namespace
      kubernetes.core.k8s:
        kind: Namespace
        name: "{{ namespace_name }}"
        state: present
      when: namespace_check.resources | length == 0

    - name: Run clickhouse backup ansible playbook
      command: ansible-playbook backup/playbook.yaml
      register: clickhouse_backup_playbook
      ignore_errors: false

    - name: Check if ClickHouse Operator is installed
      kubernetes.core.k8s_info:
        kind: Deployment
        name: altinity-clickhouse-operator
        namespace: "{{ namespace_name }}"
      register: operator_check
      changed_when: false

    - name: Add ClickHouse Operator helm repo
      command: helm repo add altinity-clickhouse-operator https://altinity.github.io/clickhouse-operator
      register: helm_repo_add
      ignore_errors: true

    - name: Update helm repo
      command: helm repo update
      register: helm_repo_update
      ignore_errors: true

    - name: Install ClickHouse Operator
      command: helm install altinity-clickhouse-operator altinity-clickhouse-operator/altinity-clickhouse-operator --namespace {{ namespace_name }}
      register: helm_install
      ignore_errors: true

    # - name: Wait for ClickHouse Operator to be ready
    #   kubernetes.core.k8s_info:
    #     kind: Deployment
    #     name: altinity-clickhouse-operator
    #     namespace: "{{ namespace_name }}"
    #   register: operator_ready
    #   until: operator_ready.resources[0].status.readyReplicas == 1
    #   retries: 5
    #   delay: 10

    - name: Create Persistent Volume
      kubernetes.core.k8s:
        state: present
        src: ch-pv.yaml
        namespace: "{{ namespace_name }}"
      register: persistent_volume
      ignore_errors: false

    - name: Create ClickHouse Installation
      kubernetes.core.k8s:
        state: present
        src: clickhouse.yaml
        namespace: "{{ namespace_name }}"
      register: clickhouse_installation
      ignore_errors: false

    - name: Create Ingress
      kubernetes.core.k8s:
        state: present
        src: ingress.yaml
        namespace: "{{ namespace_name }}"
      register: ingress
      ignore_errors: false
