apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-zookeeper-datadir-0
  labels:
    type: zookeeper-data
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  mountOptions:
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - hard
    - intr
    - timeo=600
  nfs:
    path: /mnt/nfs-storage/k8s-storage/zookeeper/datadir-0
    server: "192.168.0.5"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-zookeeper-datadir-1
  labels:
    type: zookeeper-data
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  mountOptions:
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - hard
    - intr
    - timeo=600
  nfs:
    path: /mnt/nfs-storage/k8s-storage/zookeeper/datadir-1
    server: "192.168.0.5"
