apiVersion: v1
kind: PersistentVolume
metadata:
  name: clickhouse-backup-pv
  labels:
    type: clickhouse-backup
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /mnt/clickhouse/backup
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickhouse-backup-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-path
  selector:
    matchLabels:
      type: clickhouse-backup
