apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-backup-config
data:
  config.yml: |
    general:
      remote_storage: s3
      max_file_size: 1073741824
      backups_to_keep_local: 3
      backups_to_keep_remote: 5
      log_level: info
      allow_empty_backups: false
      download_concurrency: 1
      upload_concurrency: 1
      download_max_bytes_per_second: 0
      upload_max_bytes_per_second: 0
      object_disk_server_side_copy_concurrency: 32
      allow_object_disk_streaming: false
      restore_schema_on_cluster: "replcluster"
      upload_by_part: true
      download_by_part: true
      use_resumable_state: true
      restore_database_mapping: {}
      restore_table_mapping: {}
      retries_on_failure: 3
      retries_pause: 5s
      watch_interval: 1h
      full_interval: 24h
      watch_backup_name_template: "shard{shard}-{type}-{time:20060102150405}"
      sharded_operation_mode: none
      cpu_nice_priority: 15
      io_nice_priority: "idle"
      rbac_backup_always: true
      rbac_resolve_conflicts: "recreate"

    clickhouse:
      username: test_user
      password: "test_password"
      host: clickhouse-monitoring-demo
      port: 9000
      disk_mapping: {}
      skip_tables:
        - system.*
        - INFORMATION_SCHEMA.*
        - information_schema.*
      skip_table_engines: []
      skip_disks: []
      skip_disk_types: []
      timeout: 5m
      freeze_by_part: false
      freeze_by_part_where: ""
      secure: false
      skip_verify: false
      sync_replicated_tables: true
      tls_key: ""
      tls_cert: ""
      tls_ca: ""
      log_sql_queries: true
      debug: false
      config_dir: "/var/lib/clickhouse"
      restart_command: ""
      ignore_not_exists_error_during_freeze: true
      check_replicas_before_attach: true
      default_replica_path: "/clickhouse/tables/{cluster}/{shard}/{database}/{table}"
      default_replica_name: "{replica}"
      use_embedded_backup_restore: false
      embedded_backup_disk: ""
      backup_mutations: true
      restore_as_attach: false
      check_parts_columns: true
      max_connections: 0

    s3:
      access_key: "VSMrbS2nfSCzqHalqwPa"
      secret_key: "Ty9vVw3uTLzi6I0ExBc3Detd5S4XCW4rknWKvRSc"
      bucket: "clickhouse-backup"
      endpoint: "http://minio.minio.svc.cluster.local:9000"
      region: "ap-south-1"
      path: "monitoring-demo"
      compression_format: tar
      compression_level: 1
      path_style: true
      force_path_style: true  # Adding this as well
      disable_ssl: true      # Making sure SSL is completely disabled
      use_presigned_url: false # Disable presigned URLs if they're causing issues

    api:
      listen: "0.0.0.0:7171"
      enable_metrics: true
      enable_pprof: false
      username: ""
      password: ""
      secure: false
      ca_cert_file: ""
      private_key_file: ""
      certificate_file: ""
      integration_tables_host: ""
      allow_parallel: true
      create_integration_tables: false
      complete_resumable_after_restart: true
      watch_is_main_process: false
