apiVersion: v1
kind: ServiceAccount
metadata:
  name: clickhouse-backup
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: clickhouse-backup
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec"]
    verbs: ["get", "list", "watch", "create"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["clickhouse.altinity.com"]
    resources: ["clickhouseinstallations"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: clickhouse-backup
subjects:
  - kind: ServiceAccount
    name: clickhouse-backup
roleRef:
  kind: Role
  name: clickhouse-backup
  apiGroup: rbac.authorization.k8s.io
