- name: Install and configure ClickHouse Backup
  hosts: localhost
  gather_facts: false

  vars:
    namespace_name: clickhouse

  tasks:
    - name: Create Persistant Volume
      kubernetes.core.k8s:
        state: present
        src: ch-backup-pv.yaml
        namespace: "{{ namespace_name }}"
      register: persistent_volume
      ignore_errors: false

    - name: Create ClickHouse Backup RBAC
      kubernetes.core.k8s:
        state: present
        src: clickhouse-backup-rbac.yaml
        namespace: "{{ namespace_name }}"
      register: clickhouse_installation
      ignore_errors: false

    - name: Create ClickHouse Backup Config
      kubernetes.core.k8s:
        state: present
        src: clickhouse-backup-config.yaml
        namespace: "{{ namespace_name }}"
      register: clickhouse_installation
      ignore_errors: false

    - name: Create ClickHouse Backup Deployment
      kubernetes.core.k8s:
        state: present
        src: clickhouse-backup-deployment.yaml
        namespace: "{{ namespace_name }}"
      register: clickhouse_installation
      ignore_errors: false
